### ISSUE TITLE
RegistryDataCache 缓存更新操作线程安全问题

### ISSUE THREAD

**Issue by chpengzh** [sofastack/sofa-dashboard#13]
目前zk在做服务注册发现的时候操作`RegistryDataCache`是在`childEvent`中调用的。

在这种情况下，无论是生产者还是消费者，其增删改事件都是在一个`watcher`线程顺序消费的，因此`RegistryDataCache`的实现可以不是线程安全的，且不存在线程安全问题。

但是registry那边的实现，是在Controller(tomcat线程池)中跟新cache

```java
/**
 * 获取服务列表
 *
 * @return
 */
@GetMapping("all")
public List<ServiceModel> queryServiceList() {
    doRefreshCache();
    List<ServiceModel> data = new ArrayList<>();
    Map<String, RpcService> rpcServices = registryDataCache.fetchService();
    for (Map.Entry<String, RpcService> rpcServiceEntry : rpcServices.entrySet()) {
        final String serviceName = rpcServiceEntry.getKey();
        ServiceModel model = fetchServiceModel(serviceName);
        data.add(model);
    }

    return data;
}
```

此时由于`RegistryDataCache`实现地非线程安全，就可能会出现问题。

解决方案是让`RegistryDataCache`实现变得线程安全，比如使用`ConcurrentHashMap#compute`更新缓存map，或者添加轻量级锁比如stampedlock等。

比如:

```java
@Override
public void addProviders(String serviceName, List<RpcProvider> providerList) {

    RpcService rpcService = services.get(serviceName);

    if (rpcService == null) {
        LOGGER.warn("receive provider registry data add, but service name is not exist now,{}",
            serviceName);
        return;
    }

    providers.compute(rpcService, (key, origin) -> { //This might be thread-safe
        if (origin == null) {
            return providerList;
        }
        List<RpcProvider> aggregate = new ArrayList<>(origin);
        aggregate.addAll(providerList);
        return aggregate;
    });
    LOGGER.info("receive provider registry data add, data is {}", providerList);
}
```

**Comment by glmapper** [comment]
> 目前zk在做服务注册发现的时候操作`RegistryDataCache`是在`childEvent`中调用的。
> 
> 在这种情况下，无论是生产者还是消费者，其增删改事件都是在一个`watcher`线程顺序消费的，因此`RegistryDataCache`的实现可以不是线程安全的，且不存在线程安全问题。
> 
> 但是registry那边的实现，是在Controller(tomcat线程池)中跟新cache
> 
> ```java
> /**
>  * 获取服务列表
>  *
>  * @return
>  */
> @GetMapping("all")
> public List<ServiceModel> queryServiceList() {
>     doRefreshCache();
>     List<ServiceModel> data = new ArrayList<>();
>     Map<String, RpcService> rpcServices = registryDataCache.fetchService();
>     for (Map.Entry<String, RpcService> rpcServiceEntry : rpcServices.entrySet()) {
>         final String serviceName = rpcServiceEntry.getKey();
>         ServiceModel model = fetchServiceModel(serviceName);
>         data.add(model);
>     }
> 
>     return data;
> }
> ```
> 
> 此时由于`RegistryDataCache`实现地非线程安全，就可能会出现问题。
> 
> 解决方案是让`RegistryDataCache`实现变得线程安全，比如使用`ConcurrentHashMap#compute`更新缓存map，或者添加轻量级锁比如stampedlock等。
> 
> 比如:
> 
> ```java
> @Override
> public void addProviders(String serviceName, List<RpcProvider> providerList) {
> 
>     RpcService rpcService = services.get(serviceName);
> 
>     if (rpcService == null) {
>         LOGGER.warn("receive provider registry data add, but service name is not exist now,{}",
>             serviceName);
>         return;
>     }
> 
>     providers.compute(rpcService, (key, origin) -> { //This might be thread-safe
>         if (origin == null) {
>             return providerList;
>         }
>         List<RpcProvider> aggregate = new ArrayList<>(origin);
>         aggregate.addAll(providerList);
>         return aggregate;
>     });
>     LOGGER.info("receive provider registry data add, data is {}", providerList);
> }
> ```

@chpengzh 感谢关注。这里其实不会有线程安全问题：
* 对于 doRefreshCache 操作只会在 注册中心是 SOFARegitry 时才会对缓存操作起作用，对于 Zookeeper 则不会。
* 在 SOFARegitry 作为注册中心的情况，每次进入页面，都会对当前缓存进行清空，然后将 REST请求到的 session 数据全量更新到缓存，所以数据不基于缓存来拿，而是通过 REST
