### ISSUE TITLE
npm i和npm start问题，急盼大神指点

### ISSUE THREAD

**Issue by lingzhy** [sofastack/sofa-dashboard#23]
npm http GET https://registry.npmjs.org/umi
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/sofa/sofa-dashboard-master/sofa-dashboard-front/npm-debug.log
npm ERR! not ok code 0
[root@10-205-208-151 sofa-dashboard-front]# npm start

> ant-design-pro@2.1.1 start /root/sofa/sofa-dashboard-master/sofa-dashboard-front
> cross-env APP_TYPE=site umi dev

sh: cross-env: command not found
npm ERR! weird error 127
npm ERR! not ok code 0

**Comment by chpengzh** [comment]
请问能提供一下执行环境么，操作系统，node版本和npm版本

**Comment by lingzhy** [comment]
> 请问能提供一下执行环境么，操作系统，node版本和npm版本
centos7.2      
node版本？  sofa-dashboard-master 下载最新的
npm -version 1.3.6

**Comment by chpengzh** [comment]
@lingzhy node 版本可以通过`node --version`指令查看，希望提供一下`/root/sofa/sofa-dashboard-master/sofa-dashboard-front/npm-debug.log` 这个日志

**Comment by lingzhy** [comment]
node -v 12.4.0,原来版本较低，问题已经解决，谢谢  @chpengzh

**Comment by jimchou800** [comment]
Execute the `nmp install inquirer` command manually
