### ISSUE TITLE
there are problems executing `mvn  install` commands

### ISSUE THREAD

**Issue by jimchou800** [sofastack/sofa-dashboard#37]
It is recommended that front-end projects not be placed in modules , because there are problems executing `mvn  install` commands

**Comment by glmapper** [comment]
> It is recommended that front-end projects not be placed in modules , because there are problems executing `mvn install` commands

Can you provide more information?

**Comment by jimchou800** [comment]
Sorry, I have solved this problem, but it can't reproduced now . Maybe it was my fault.
